parameters:
    support:
        email: 'support@maxi-booking.ru'

    #currencies
    mbh.currency.data:
      rub: {text: 'руб.', small: 'коп.', icon: 'fa fa-ruble'}
      eur: {text: '€', small: '¢', icon: 'fa fa-eur'}
      uah: {text: 'грн.', small: 'коп.', icon: 'fa fa-money'}
      kzt: {text: 'тенге', small: 'тиын', icon: 'fa fa-money'}
      gel: {text: 'Lari', small: 't', icon: 'fa fa-money'}
      usd: {text: '$', small: '$', icon: 'fa fa-usd'}

    # ReCaptcha
    mbh.recaptcha:
      site: '6Lev6AYUAAAAADL-WFxyHoaaGfya4uFBCUh09FWx'
      secret: '6Lev6AYUAAAAAIk51IMnRdGS4Im_-1h3pk-cM87a'

    mbh.weekdays: {1: 'Понедельник', 2: 'Вторник', 3: 'Среда', 4: 'Четверг', 5: 'Пятница', 6: 'Суббота', 0: 'Воскресенье'}

    mbh.mongodb:
      url: "mongodb://%mongodb_host%:%mongodb_port%/%mongodb_database%"
      db : "%mongodb_database%"

    mbh.environment: "%mbh_environment%"

    #mbh hotel config
    mbh.hotel:
      types:
        apartments: 'Апартаменты'
        recreation_center: 'База отдыха'
        guest_house: 'Гостевой дом'
        pension: 'Пансионат'
        sanatorium: 'Санаторий'
        country_club: 'Загородный клуб'
        hostel: 'Хостел'
        hotel: 'Отель'
        motel: 'Мотель'
        resort: 'Курортный отель'
        mini_hotel: 'Мини-отель'
      themes:
        сity_tour: 'Экскурсия по городу'
        budget_travel: 'Бюджетные и молодежные поездки'
        shoping: 'Шопинг'
        family_trip: 'Семейная поездка'
        international: 'Международный'
        business_trip: 'Деловая поездка'
        romantic_vacation: 'Романтический отпуск/Медовый месяц'
        interior_design: 'Дизайнерский интерьер'
        luxury_holidays: 'Отдых класса люкс'
        haute_cuisine: 'Изысканная кухня'
        country_holidays: 'Загородный отдых'
        homestead: 'Усадьба'
        nature: 'Природа/Дикая флора и фауна'
        spa: 'Спа/Оздоровительные процедуры'
        ecological: 'Экологический'
        ski: 'Горы/лыжи'
        adventure: 'Приключение'
        sport: 'Спорт'
        beach: 'Пляж/Побережье'
        city: 'Городской'
      facilities:
        # Здание
        building:
          parking: 'facilities.parking'
          fitness: 'facilities.fitness'
          swimming: 'facilities.swimming'
          sauna: 'facilities.sauna'
          internet: 'facilities.internet'
          shopping: 'facilities.shopping'
          restaurant: 'facilities.restaurant'
          cafeteria: 'facilities.cafeteria'
          fastfood: 'facilities.fastfood'
          beach-bar: 'facilities.beach-bar'
          beer: 'facilities.beer'
          baggage-safe: 'facilities.baggage-safe'
          baggage-man: 'facilities.baggage-man'
          disc-floppy: 'facilities.disc-floppy'
          spa: 'facilities.spa'
          lounge: 'facilities.lounge'
          skiing: 'facilities.skiing'
          chapel: 'facilities.chapel'

        # Правила размещения
        rules:
          animals: 'facilities.animals'
          no-animals: 'facilities.no-animals'
          credit-card: 'facilities.credit-card'
          cc-nc: 'facilities.cc-nc'
          breakfast: 'facilities.breakfast'

        # Возможности
        ability:
          reception: 'facilities.reception'
          wifi: 'facilities.wifi'
          free-wifi: 'facilities.free-wifi'
          car-side: 'facilities.car-side'
          taxi: 'facilities.taxi'
          menu: 'facilities.menu'
          travelling: 'facilities.travelling'
          lock: 'facilities.lock'
          camera: 'facilities.camera'
          keys: 'facilities.keys'
          metro: 'facilities.metro'
          disfacilities: 'facilities.disability'
          blind: 'facilities.blind'

        # Тип комнаты
        roomtype:
          maleroom: 'facilities.maleroom'
          femaleroom: 'facilities.femaleroom'
          ruby: 'facilities.ruby'

        # Мебель
        furniture:
          bed: 'facilities.bed'
          double-bed: 'facilities.double-bed'
          sofa: 'facilities.sofa'
          armchair: 'facilities.armchair'
          table: 'facilities.table'
          platen: 'facilities.platen'
          chair: 'facilities.chair'
          dresstable: 'facilities.dresstable'
          wardrobe: 'facilities.wardrobe'
          bookcase: 'facilities.bookcase'
          torchere: 'facilities.torchere'
          safe: 'facilities.safe'

        # Еда
        food:
          kitchen: 'facilities.kitchen'
          bar: 'facilities.bar'
          teapot: 'facilities.teapot'
          coffee: 'facilities.coffee'
          fridge: 'facilities.fridge'

        # Удобства
        amenity:
          bath: 'facilities.bath'
          sink: 'facilities.sink'
          shower: 'facilities.shower'
          toilets: 'facilities.toilets'
          ws: 'facilities.ws'
          sign-in: 'facilities.sign-in'

        # Техника
        technical:
          telephone: 'facilities.telephone'
          fan: 'facilities.fan'
          conditioner: 'facilities.conditioner'
          modern-tv: 'facilities.modern-tv'
          old-tv: 'facilities.old-tv'
          homecinema: 'facilities.homecinema'
          washmachine: 'facilities.washmachine'
          radio: 'facilities.radio'
          iron: 'facilities.iron'
          plug: 'facilities.plug'
          board-games: 'facilities.board-games'

    #mbhs
    mbh.mbhs:
      mbhs: 'aHR0cHM6Ly9tYmhzLm1heGlib29raW5nLnJ1Lw=='
      key: '%mbhs_key%'

    #mbh services
    mbh.services:
      calcTypes:
        per_stay: 'за весь срок'
        per_night: 'за cутки'
        not_applicable: 'за услугу'
        day_percent: 'за услугу (% от цены за сутки)'

    #mailer
    mbh.mailer:
      fromText: 'MaxiBooking'
      fromMail:  "%from_email%"
      subject: 'Сообщение от MaxiBooking'
      template: 'MBHBaseBundle:Mailer:base.html.twig'

    #параметры онлайн формы
    mbh.online.form:
          messages: true
          payment_types:
            by_receipt_full: 'Оплата по счету через банк (100%)'
            by_receipt_half: 'Оплата по счету через банк (50%)'
            by_receipt_first_day: 'Оплата по счету через банк (одни сутки)'
            in_hotel: 'Оплата при заселении'
            online_full: 'Онлайн оплата (100%)'
            online_first_day: 'Онлайн оплата (одни сутки)'
            online_half: 'Онлайн оплата (50%)'

    #платежные системы
    mbh.payment_systems:
      moneymail: 'MoneyMail'
      robokassa: 'Robokassa'
      payanyway: 'PayAnyWay'
      uniteller: 'Uniteller'
      rbk: 'Rbk'
      paypal: 'PayPal'
      rnkb: 'Rnkb'
      invoice: 'По счету'
    mbh.payment_systems.default: uniteller
    mbh.payment_systems.change: "%mbh_payment_systems_change%"

    mbh.taxation:
      rate_codes:
        -1: не облагается НДС
        0: облагается НДС по ставке 0%
        10: облагается НДС по ставке 10%
        18: облагается НДС по ставке 18%
        110: облагается НДС по ставке 10/110
        118: облагается НДС по ставке 18/118
      system_codes:
        0: Общая система налогообложения
        1: Упрощенная система налогообложения (Доход)
        2: Упрощенная СН (Доход минус Расход)
        3: Единый налог на вмененный доход
        4: Единый сельскохозяйственный налог
        5: Патентная система налогообложения

    #параметры Channel manager
    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель'
          service: 'mbh.channelmanager.vashotel'
          password: jguuE26t684Fl
        booking:
          title: 'Booking.com'
          service: 'mbh.channelmanager.booking'
          username: Maxibooking-live
          password: 'B*I)UB:G.E:sGs7mVy-X1r(H))gnAUx?*uyM:ZC/'
        ostrovok:
          title: 'Ostrovok'
          service: 'mbh.channelmanager.ostrovok'
          username: 59a0ed03e26016ab59a3fe1cfdeb9479
          password: 1b9952573d01aef185ca3edc17432aab
        myallocator:
          title: 'MyAllocator'
          service: 'mbh.channelmanager.myallocator'
          api_username: maxipanev
          api_password: VCuMhanjdxiC
          vendor_password: 0Rp0XJGubJ9rfoUy4niNGcBPErf20VJZ
          url: http://mbhs.maxibooking.ru/client/channelmanager/push/myallocator
        expedia:
          title: 'Expedia'
          service: 'mbh.channelmanager.expedia'
        hundred_one_hotels:
          title: '101 Отель'
          service: 'mbh.channelmanager.hundred_one_hotels'
        oktogo:
          title: 'Oktogo'
          service: 'mbh.channelmanager.oktogo'
          api_username: .maxiBooking_api
          api_password: qdcmBz9K

    #параметры логов
    mbh.logs.max: 100

    #параметры отчетов
    mbh.reports.accommodation.rooms.max: 15

    #Типы отчетов аналитики
    mbh.analytics.types:
        sales_packages: "Динамика продаж по количеству броней"
        sales_cash: "Динамика продаж по стоимости броней"
        sales_cash_documents: "Динамика продаж в полученных деньгах"
        sales_sources: "Источники продаж"
        hotel_occupancy: "Заполняемость отеля"
        sales_services: "Динамика реализации услуг"
        sales_managers: "Менеджеры и брони"


    #Цели приезда
    mbh.package.arrivals:
        service: Служебная
        tourism: Туризм
        business: Деловая
        study: Учеба
        work: Работа
        private: Частная
        residence: Транзит
        humanitarian: Гуманитарная
        other: Другая

    #Цели приезда
    mbh.package.statuses:
        offline: { title: "Обычная", class: "info", icon: "fa fa-paper-plane-o"}
        online: { title: "Онлайн", class: "success", icon: "fa fa-globe"}
        channel_manager: { title: "Channel manager", class: "danger", icon: "fa fa-cloud-download"}


    #Статусы задач
    mbh.task.statuses:
        open: { title: "Открыта", class: "success"}
        process: { title: "В процессе", class: "info"}
        closed: { title: "Закрыта", class: "danger"}

    #Приоритет задач
    mbh.tasktype.priority:
        1: low
        2: average
        3: high

    #Типы документов
    mbh.order.document.types:
        passport: package.document.type_passport
        foreign_passport: package.document.type_foreign_passport
        insurance: package.document.type_insurance
        birth_certificate: package.document.type_birth_certificate
        military: package.document.type_military
        accommodation_voucher: package.document.type_accommodation_voucher
        shuttle_voucher: package.document.type_shuttle_voucher
        sertives_voucher: package.document.type_sertives_voucher
        complex: package.document.type_complex
        congirmation_account: package.document.type_congirmation_account
        invoice_for_payment: package.document.type_invoice_for_payment
        contract: package.document.type_contract
        extra_argument: package.document.type_extra_argument
        air_tickets: package.document.type_air_tickets
        train_tickets: package.document.type_train_tickets
        info: package.document.type_info
        letter: package.document.type_letter
        other: package.document.type_other

    #Виды способов оплаты
    mbh.cash.methods:
        cash: "Наличные"
        cashless: "Безнал"
        electronic: "Электронный"
    
    #Типы операций с кассой
    mbh.cash.operations:
        in: "Поступление"
        out: "Расход"
        #fine: "Штраф"
        fee: "Комиссия"

    #М/Ж
    mbh.gender.types:
        male: "Мужчина"
        female: "Женщина"
        unknown: "Неизвестно"

    mbh.organization.types:
        contragents: 'Контрагенты'
        my: 'Мои организации'

    mbh.payer_organization:
        name: 'ООО "Наличные средства"'
        checking_account: '44400000000000000000'
        inn: '7700000000'
        kpp: '770000000'
        bank: '""'
        bank_bik: '000000000'
        correspondent_account: '33300000000000000000'
        accountant_fio: ''

    mbh.room_status_icons:
        repair: 'tools'
        cleaning: 'clean'
        reserve: 'lock'
        other: 'clock'

    # BaseBundle/Resources/translations/messages.ru.yml
    mbh.languages:
        - en
        - ru
        
    mbh.warehouse.operations:
        in: "Приход"
        out: "Расход"

    #Указаны идентификаторы для переводов. Переводы хранятся в HotelBundle
    mbh.smoking_policy:
        47:	form.hotelExtendedType.all_rooms_non_smoking
        198: form.hotelExtendedType.non_smoking_room
        268: form.hotelExtendedType.all_public_areas_non_smoking
        900201:	form.hotelExtendedType.smoking_permitted_in_designated_areas_and_rooms

