parameters:
    #currencies
    mbh.currency.ratio.fix: %currency_ratio_fix%
    mbh.currency.data:
      rub: {text: 'руб.', small: 'коп.', icon: 'fa fa-ruble'}
      eur: {text: '€', small: '¢', icon: 'fa fa-eur'}
      uah: {text: 'грн.', small: 'коп.', icon: 'fa fa-money'}
      kzt: {text: 'тенге', small: 'тиын', icon: 'fa fa-money'}
      gel: {text: 'Lari', small: 't', icon: 'fa fa-money'}

    # ReCaptcha
    mbh.recaptcha:
      site: '6Lev6AYUAAAAADL-WFxyHoaaGfya4uFBCUh09FWx'
      secret: '6Lev6AYUAAAAAIk51IMnRdGS4Im_-1h3pk-cM87a'

    #timezone. default - deafult server timezone
    mbh.timezone: "%mbh_timezone%"

    mbh.weekdays: {1: 'Понедельник', 2: 'Вторник', 3: 'Среда', 4: 'Четверг', 5: 'Пятница', 6: 'Суббота', 0: 'Воскресенье'}

    mbh.mongodb:
      url: "%mongodb_url%"
      db : "%mongodb_database%"

    mbh.environment: "%mbh_environment%"

    #mbh hotel config
    mbh.hotel:
      types:
        apartments: 'Апартаменты'
        recreation_center: 'База отдыха'
        guest_house: 'Гостевой дом'
        pension: 'Пансионат'
        sanatorium: 'Санаторий'
        country_club: 'Загородный клуб'
        hostel: 'Хостел'
        hotel: 'Отель'
        motel: 'Мотель'
        resort: 'Курортный отель'
        mini_hotel: 'Мини-отель'
      themes:
        сity_tour: 'Экскурсия по городу'
        budget_travel: 'Бюджетные и молодежные поездки'
        shoping: 'Шопинг'
        family_trip: 'Семейная поездка'
        international: 'Международный'
        business_trip: 'Деловая поездка'
        romantic_vacation: 'Романтический отпуск/Медовый месяц'
        interior_design: 'Дизайнерский интерьер'
        luxury_holidays: 'Отдых класса люкс'
        haute_cuisine: 'Изысканная кухня'
        country_holidays: 'Загородный отдых'
        homestead: 'Усадьба'
        nature: 'Природа/Дикая флора и фауна'
        spa: 'Спа/Оздоровительные процедуры'
        ecological: 'Экологический'
        ski: 'Горы/лыжи'
        adventure: 'Приключение'
        sport: 'Спорт'
        beach: 'Пляж/Побережье'
        city: 'Городской'
      facilities:
        # Здание
        building:
          parking: 'Парковка'
          fitness: 'Фитнес-центр'
          swimming: 'Бассейн'
          sauna: 'Баня/Сауна'
          internet: 'Интернет-класс'
          shopping: 'Шопинг'
          restaurant: 'Ресторан'
          cafeteria: 'Кафетерий'
          fastfood: 'Закусочная'
          beach-bar: 'Бар на пляже'
          beer: 'Пивной бар'
          baggage-safe: 'Комната хранения'
          baggage-man: 'Носильщик'
          disc-floppy: 'Гостевой офис'
          spa: 'Спа-салон'
          lounge: 'Зона отдыха'
          skiing: 'Лыжная трасса'
          chapel: 'Часовня'

        # Правила размещения
        rules:
          animals: 'Разрешены животные'
          no-animals: 'Размещение с животными запрещено'
          credit-card: 'Кредитные карты принимаются'
          cc-nc: 'Иностранная валюта не принимается'
          breakfast: 'Завтрак включен'

        # Возможности
        ability:
          reception: 'Круглосуточная стойка регистрации'
          wifi: 'Wi-Fi'
          free-wifi: 'Бесплатный Wi-Fi'
          car-side: 'Прокат автомобиля'
          taxi: 'Заказ такси'
          menu: 'Заказ еды'
          travelling: 'Заказ экскурсий'
          lock: 'Контроль доступа'
          camera: 'Видеонаблюдение'
          keys: 'Электронные замки'
          metro: 'Близость метрополитена'
          disability: 'Доступ для маломобильных граждан'
          blind: 'Доступ для слепых граждан'

        # Тип комнаты
        roomtype:
          maleroom: 'Мужская комната'
          femaleroom: 'Женская комната'
          ruby: 'Люкс'

        # Мебель
        furniture:
          bed: 'Односпальная кровать'
          double-bed: 'Двуспальная кровать'
          sofa: 'Диван-кровать'
          armchair: 'Кресло'
          table: 'Стол'
          platen: 'Столик'
          chair: 'Стул'
          dresstable: 'Трюмо'
          wardrobe: 'Платяной шкаф'
          bookcase: 'Книжный шкаф'
          torchere: 'Торшер'
          safe: 'Сейф'

        # Еда
        food:
          kitchen: 'Кухня'
          bar: 'Минибар'
          teapot: 'Чайник'
          coffee: 'Кофе-машина'
          fridge: 'Холодильник'

        # Удобства
        amenity:
          bath: 'Ванная'
          sink: 'Умывальник'
          shower: 'Душ'
          toilets: 'Туалет'
          ws: 'Унитаз'
          sign-in: 'Запасной выход'

        # Техника
        technical:
          telephone: 'Телефон'
          fan: 'Вентилятор'
          conditioner: 'Кондиционер'
          modern-tv: 'Современный телевизор'
          old-tv: 'Телевизор'
          homecinema: 'Домашний кинотеатр'
          washmachine: 'Стиральная машина'
          radio: 'Радио'
          iron: 'Утюг'
          plug: 'Электророзетка'
          board-games: 'Настольные игры'

    #mbhs
    mbh.mbhs:
      mbhs: 'aHR0cDovL21iaHMubWF4aWJvb2tpbmcucnUv'
      key: '%mbhs_key%'

    #mbh services
    mbh.services:
      calcTypes:
        per_stay: 'за весь срок'
        per_night: 'за cутки'
        not_applicable: 'за услугу'
        day_percent: 'за услугу (% от цены за сутки)'

    #mailer
    mbh.mailer:
      fromText: 'MaxiBooking'
      fromMail:  %from_email%
      subject: 'Сообщение от MaxiBooking'
      template: 'MBHBaseBundle:Mailer:base.html.twig'

    #параметры онлайн формы
    mbh.online.form:
          sites: %online_form_sites%
          packages_max: 5
          messages: true
          form:
            width: '300px'
            height: 'auto'
          result:
            width: 'auto'
            height: 'auto'
            url: %online_form_result_url%
          payment_types:
            in_hotel: 'Оплата при заселении'
            online_full: 'Онлайн оплата (100%)'
            online_first_day: 'Онлайн оплата (одни сутки)'
            online_half: 'Онлайн оплата (50%)'

    #платежные системы
    mbh.payment_systems:
      moneymail: 'MoneyMail'
      robokassa: 'Robokassa'
      payanyway: 'PayAnyWay'
      uniteller: 'Uniteller'
      rbk: 'Rbk'
    mbh.payment_systems.default: uniteller
    mbh.payment_systems.change: %mbh_payment_systems_change%

    #параметры Channel manager
    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель'
          service: 'mbh.channelmanager.vashotel'
          password: jguuE26t684Fl
        booking:
          title: 'Booking.com'
          service: 'mbh.channelmanager.booking'
          username: Maxibooking-live
          password: 'B*I)UB:G.E:sGs7mVy-X1r(H))gnAUx?*uyM:ZC/'
        ostrovok:
          title: 'Ostrovok'
          service: 'mbh.channelmanager.ostrovok'
          username: 722ac50470d8af33d509c069ccb83443
          password: edfdfba3f6902eb63aa254935e9a8a36
        myallocator:
          title: 'MyAllocator'
          service: 'mbh.channelmanager.myallocator'
          api_username: maxipanev
          api_password: VCuMhanjdxiC
          vendor_password: 0Rp0XJGubJ9rfoUy4niNGcBPErf20VJZ
          url: http://mbhs.maxibooking.ru/client/channelmanager/push/myallocator
        expedia:
          title: 'Expedia'
          service: 'mbh.channelmanager.expedia'

    #параметры логов
    mbh.logs.max: 100

    #параметры отчетов
    mbh.reports.accommodation.rooms.max: 15

    #Типы отчетов аналитики
    mbh.analytics.types:
        sales_packages: "Динамика продаж по количеству броней"
        sales_cash: "Динамика продаж по стоимости броней"
        sales_cash_documents: "Динамика продаж в полученных деньгах"
        sales_sources: "Источники продаж"
        hotel_occupancy: "Заполняемость отеля"
        sales_services: "Динамика реализации услуг"
        sales_managers: "Менеджеры и брони"


    #Цели приезда
    mbh.package.arrivals:
        service: Служебная
        tourism: Туризм
        business: Деловая
        study: Учеба
        work: Работа
        private: Частная
        residence: Транзит
        humanitarian: Гуманитарная
        other: Другая

    #Время заезда/выезда по умолчанию
    mbh.package.arrival.time: %mbh_package_arrival_time%
    mbh.package.departure.time: %mbh_package_departure_time%
    
    #Просроченные брони
    mbh.package.notpaid.time: '%mbh_package_notpaid_time%'

    #Цели приезда
    mbh.package.statuses:
        offline: { title: "Обычная", class: "info", icon: "fa fa-paper-plane-o"}
        online: { title: "Онлайн", class: "success", icon: "fa fa-globe"}
        channel_manager: { title: "Channel manager", class: "danger", icon: "fa fa-cloud-download"}


    #Статусы задач
    mbh.task.statuses:
        open: { title: "Открыта", class: "success"}
        process: { title: "В процессе", class: "info"}
        closed: { title: "Закрыта", class: "danger"}

    #Приоритет задач
    mbh.tasktype.priority:
        1: low
        2: average
        3: high

    #Типы документов
    mbh.order.document.types:
        passport: package.document.type_passport
        foreign_passport: package.document.type_foreign_passport
        insurance: package.document.type_insurance
        birth_certificate: package.document.type_birth_certificate
        military: package.document.type_military
        accommodation_voucher: package.document.type_accommodation_voucher
        shuttle_voucher: package.document.type_shuttle_voucher
        sertives_voucher: package.document.type_sertives_voucher
        complex: package.document.type_complex
        congirmation_account: package.document.type_congirmation_account
        invoice_for_payment: package.document.type_invoice_for_payment
        contract: package.document.type_contract
        extra_argument: package.document.type_extra_argument
        air_tickets: package.document.type_air_tickets
        train_tickets: package.document.type_train_tickets
        info: package.document.type_info
        letter: package.document.type_letter
        other: package.document.type_other

    #Виды способов оплаты
    mbh.cash.methods:
        cash: "Наличные"
        cashless: "Безнал"
        electronic: "Электронный"
    
    #Типы операций с кассой
    mbh.cash.operations:
        in: "Поступление"
        out: "Расход"
        #fine: "Штраф"
        fee: "Комиссия"

    #М/Ж
    mbh.gender.types:
        male: "Мужчина"
        female: "Женщина"
        unknown: "Неизвестно"

    mbh.organization.types:
        contragents: 'Контрагенты'
        my: 'Мои организации'

    mbh.payer_organization:
        name: 'ООО "Наличные средства"'
        checking_account: '44400000000000000000'
        inn: '7700000000'
        kpp: '770000000'
        bank: '""'
        bank_bik: '000000000'
        correspondent_account: '33300000000000000000'
        accountant_fio: ''

    mbh.room_status_icons:
        repair: 'tools'
        cleaning: 'clean'
        reserve: 'lock'
        other: 'clock'

    # BaseBundle/Resources/translations/messages.ru.yml
    mbh.languages:
        - en
        - ru
        
    mbh.warehouse.operations:
        in: "Приход"
        out: "Расход"


