parameters:

    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель.RU'
          service: 'mbh.channelmanager.vashotel'
        booking:
          title: 'Booking.com'
          service: 'mbh.channelmanager.booking'
          username: maxibookingXML
          password: bMBhv6tds5i
        ostrovok:
          title: 'Ostrovok'
          service: 'mbh.channelmanager.ostrovok'
          username: 59a0ed03e26016ab59a3fe1cfdeb9479
          password: 1b9952573d01aef185ca3edc17432aab
        myallocator:
          title: 'MyAllocator'
          service: 'mbh.channelmanager.myallocator'
          api_username: maxipanev
          api_password: VCuMhanjdxiC
          vendor_password: 0Rp0XJGubJ9rfoUy4niNGcBPErf20VJZ
          url: http://mbhs.maxibooking.ru/client/channelmanager/push/myallocator
        hundred_one_hotels:
          title: '101 Отель'
          service: 'mbh.channelmanager.hundred_one_hotels'
        oktogo:
          title: 'Oktogo'
          service: 'mbh.channelmanager.oktogo'
          api_username: .maxiBooking_api
          api_password: qdcmBz9K
        expedia:
          title: 'Expedia'
          service: 'mbh.channelmanager.expedia'

    mbh.mbhs:
          mbhs: 'aHR0cDovL21iaHMuaC9hcHBfZGV2LnBocC8=' #http://mbhs.h/app_dev.php/
          key: 2743004999743693560727430049997436935607
