security:
  role_hierarchy:
    ROLE_ASYNC_SEARCH: ~
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_HOTEL
      - ROLE_GROUP
      - ROLE_CITY
      - ROLE_LOGS
      - ROLE_CASH
      - ROLE_CLIENT_CONFIG
      - ROLE_DOCUMENT_TEMPLATES
      - ROLE_HOUSING
      - ROLE_ROOM
      - ROLE_ROOM_TYPE
      - ROLE_TASK_MANAGER
      - ROLE_MANAGER
      - ROLE_OVERVIEW
      - ROLE_PRICE_CACHE
      - ROLE_RESTRICTION
      - ROLE_ROOM_CACHE
      - ROLE_SERVICE
      - ROLE_SERVICE_CATEGORY
      - ROLE_TARIFF
      - ROLE_SPECIAL
      - ROLE_USER
      - ROLE_CHANNEL_MANAGER
      - ROLE_ONLINE_FORM
      - ROLE_ONLINE_PAYMENT_FORM
      - ROLE_POLLS
      - ROLE_REPORTS
      - ROLE_PACKAGE
      - ROLE_SOURCE
      - ROLE_PROMOTION
      - ROLE_ROOM_TYPE_CATEGORY
      - ROLE_WORK_SHIFT
      - ROLE_WAREHOUSE
      - ROLE_RESTAURANT_SENIOR_MANAGER

    ROLE_LOGS: [ROLE_BASE_USER]
    ROLE_USER: [ROLE_USER_VIEW, ROLE_USER_NEW, ROLE_USER_EDIT, ROLE_USER_DELETE, ROLE_USER_PROFILE]
    ROLE_GROUP: [ROLE_GROUP_VIEW, ROLE_GROUP_NEW, ROLE_GROUP_EDIT, ROLE_GROUP_DELETE]
    ROLE_HOTEL: [ROLE_HOTEL_VIEW, ROLE_HOTEL_NEW, ROLE_HOTEL_EDIT, ROLE_HOTEL_DELETE]
    ROLE_CITY: [ROLE_CITY_VIEW]
    ROLE_CASH: [ROLE_CASH_VIEW, ROLE_CASH_NEW, ROLE_CASH_EDIT, ROLE_CASH_DELETE, ROLE_CASH_CONFIRM, ROLE_CASH_NUMBER]
    ROLE_CLIENT_CONFIG: [ROLE_CLIENT_CONFIG_VIEW, ROLE_CLIENT_CONFIG_EDIT]
    ROLE_DOCUMENT_TEMPLATES: [ROLE_DOCUMENT_TEMPLATES_VIEW, ROLE_DOCUMENT_TEMPLATES_NEW, ROLE_DOCUMENT_TEMPLATES_EDIT, ROLE_DOCUMENT_TEMPLATES_DELETE]
    ROLE_ROOM_FUND: [ROLE_ROOM_TYPE, ROLE_ROOM]

    ROLE_HOUSING: [ROLE_HOUSING_VIEW, ROLE_HOUSING_NEW, ROLE_HOUSING_EDIT, ROLE_HOUSING_DELETE]

    ROLE_ROOM_TYPE: [ROLE_ROOM_TYPE_VIEW, ROLE_ROOM_TYPE_NEW, ROLE_ROOM_TYPE_EDIT, ROLE_ROOM_TYPE_DELETE]
    ROLE_ROOM: [ROLE_ROOM_VIEW, ROLE_ROOM_NEW, ROLE_ROOM_EDIT, ROLE_ROOM_DELETE, ROLE_ROOM_STATUS_EDIT]

    ROLE_CHANNEL_MANAGER: [ROLE_BOOKING, ROLE_VASHOTEL, ROLE_OSTROVOK, ROLE_OKTOGO, ROLE_HOTELINN, ROLE_MYALLOCATOR, ROLE_101HOTELS]
    ROLE_ONLINE_FORM: [ROLE_ONLINE_FORM_VIEW, ROLE_ONLINE_FORM_NEW, ROLE_ONLINE_FORM_EDIT, ROLE_ONLINE_FORM_DELETE]
    ROLE_POLLS: [ROLE_BASE_USER]

    ROLE_ONLINE_PAYMENT_FORM:
          - ROLE_ONLINE_PAYMENT_FORM_VIEW
          - ROLE_ONLINE_PAYMENT_FORM_NEW
          - ROLE_ONLINE_PAYMENT_FORM_EDIT
          - ROLE_ONLINE_PAYMENT_FORM_DELETE

    ROLE_PACKAGE:
      - ROLE_SEARCH
      - ROLE_PACKAGE_VIEW
      - ROLE_PACKAGE_NEW
      - ROLE_ORDER_EDIT
      - ROLE_PACKAGE_EDIT
      - ROLE_PACKAGE_UNLOCK
      - ROLE_ORDER_PAYER
      - ROLE_PACKAGE_GUESTS
      - ROLE_PACKAGE_SERVICES
      - ROLE_PACKAGE_ACCOMMODATION
      - ROLE_ORDER_DOCUMENTS
      - ROLE_DOCUMENTS_GENERATOR
      - ROLE_ORDER_CASH_DOCUMENTS
      - ROLE_PACKAGE_DELETE
      - ROLE_PACKAGE_VIEW_ALL
      - ROLE_PACKAGE_EDIT_ALL
      - ROLE_PACKAGE_DELETE_ALL
      - ROLE_PACKAGE_DOCS
      - ROLE_ORDER_AUTO_CONFIRMATION
      - ROLE_INDIVIDUAL_PROMOTION_ADD
      - ROLE_PROMOTION_ADD
      - ROLE_SPECIAL_ADD
      - ROLE_DISCOUNT_ADD
      - ROLE_PACKAGE_PRICE_EDIT
      - ROLE_FORCE_BOOKING
      - ROLE_NO_OWN_ONLINE_VIEW
      - ROLE_PACKAGE_DELETE_REASONS_CATEGORY
      - ROLE_PACKAGE_DELETE_REASONS

    ROLE_PACKAGE_VIEW_ALL: [ROLE_PACKAGE_VIEW]
    ROLE_PACKAGE_DELETE_ALL: [ROLE_PACKAGE_DELETE]

    ROLE_REPORTS:
      - ROLE_ANALYTICS
      - ROLE_TOURIST_REPORT
      - ROLE_PORTER_REPORT
      - ROLE_ACCOMMODATION_REPORT
      - ROLE_SERVICES_REPORT
      - ROLE_ORGANIZATION
      - ROLE_MANAGERS_REPORT
      - ROLE_POLLS_REPORT
      - ROLE_WINDOWS_REPORT
      - ROLE_ROOMS_REPORT
      - ROLE_WINDOWS_PACKAGING
      - ROLE_PACKAGE_MOVING
      - ROLE_DYNAMIC_SALES
      - ROLE_DISTRIBUTION_BY_DAYS_OF_WEEK_REPORT
      - ROLE_DAILY_REPORT_BY_PACKAGES

    ROLE_TOURIST_REPORT: [ROLE_TOURIST]
    ROLE_TOURIST: [ROLE_TOURIST_VIEW, ROLE_TOURIST_NEW, ROLE_TOURIST_EDIT, ROLE_TOURIST_DELETE]
    ROLE_ORGANIZATION: [ROLE_ORGANIZATION_VIEW, ROLE_ORGANIZATION_NEW, ROLE_ORGANIZATION_EDIT, ROLE_ORGANIZATION_DELETE]

    ROLE_SOURCE: [ROLE_SOURCE_VIEW, ROLE_SOURCE_NEW, ROLE_SOURCE_EDIT, ROLE_SOURCE_DELETE]

    ROLE_TASK_MANAGER: [ROLE_TASK, ROLE_TASK_TYPE, ROLE_TASK_TYPE_CATEGORY]
    ROLE_TASK: [ROLE_TASK_VIEW, ROLE_TASK_OWN_VIEW, ROLE_TASK_NEW, ROLE_TASK_EDIT, ROLE_TASK_DELETE]
    ROLE_TASK_TYPE: [ROLE_TASK_TYPE_VIEW, ROLE_TASK_TYPE_NEW, ROLE_TASK_TYPE_EDIT, ROLE_TASK_TYPE_DELETE]
    ROLE_TASK_TYPE_CATEGORY: [ROLE_TASK_TYPE_CATEGORY_VIEW, ROLE_TASK_TYPE_CATEGORY_NEW, ROLE_TASK_TYPE_CATEGORY_EDIT, ROLE_TASK_TYPE_CATEGORY_DELETE]

    ROLE_PRICE_CACHE: [ROLE_PRICE_CACHE_VIEW, ROLE_PRICE_CACHE_EDIT, ROLE_OVERVIEW]
    ROLE_RESTRICTION: [ROLE_RESTRICTION_VIEW, ROLE_RESTRICTION_EDIT, ROLE_OVERVIEW]
    ROLE_ROOM_CACHE: [ROLE_ROOM_CACHE_VIEW, ROLE_ROOM_CACHE_EDIT, ROLE_OVERVIEW]

    ROLE_SERVICE: [ROLE_SERVICE_VIEW, ROLE_SERVICE_NEW, ROLE_SERVICE_EDIT, ROLE_SERVICE_DELETE]
    ROLE_SERVICE_CATEGORY: [ROLE_SERVICE_CATEGORY_NEW, ROLE_SERVICE_CATEGORY_EDIT, ROLE_SERVICE_CATEGORY_DELETE]
    ROLE_TARIFF: [ROLE_TARIFF_VIEW, ROLE_TARIFF_NEW, ROLE_TARIFF_EDIT, ROLE_TARIFF_DELETE]
    ROLE_SPECIAL: [ROLE_SPECIAL_VIEW, ROLE_SPECIAL_NEW, ROLE_SPECIAL_EDIT, ROLE_SPECIAL_DELETE]
    ROLE_PROMOTION: [ROLE_PROMOTION_VIEW, ROLE_PROMOTION_NEW, ROLE_PROMOTION_EDIT, ROLE_PROMOTION_DELETE]
    ROLE_ROOM_TYPE_CATEGORY: [ROLE_ROOM_TYPE_CATEGORY_VIEW, ROLE_ROOM_TYPE_CATEGORY_NEW, ROLE_ROOM_TYPE_CATEGORY_EDIT, ROLE_ROOM_TYPE_CATEGORY_DELETE]
    ROLE_WORK_SHIFT: [ROLE_WORK_SHIFT_VIEW, ROLE_WORK_SHIFT_CLOSE]
    ROLE_STAFF: [ROLE_TASK_OWN_VIEW]

    ROLE_WAREHOUSE: [ROLE_WAREHOUSE_CAT, ROLE_WAREHOUSE_ITEMS, ROLE_WAREHOUSE_RECORD, ROLE_WAREHOUSE_INVOICE]
    ROLE_WAREHOUSE_CAT: [ROLE_WAREHOUSE_CAT_VIEW, ROLE_WAREHOUSE_CAT_NEW, ROLE_WAREHOUSE_CAT_EDIT, ROLE_WAREHOUSE_CAT_DELETE]
    ROLE_WAREHOUSE_ITEMS: [ROLE_WAREHOUSE_ITEMS_VIEW, ROLE_WAREHOUSE_ITEMS_NEW, ROLE_WAREHOUSE_ITEMS_EDIT, ROLE_WAREHOUSE_ITEMS_DELETE]
    ROLE_WAREHOUSE_RECORD: [ROLE_WAREHOUSE_RECORD_VIEW, ROLE_WAREHOUSE_RECORD_NEW, ROLE_WAREHOUSE_RECORD_EDIT, ROLE_WAREHOUSE_RECORD_DELETE]
    ROLE_WAREHOUSE_INVOICE: [ROLE_WAREHOUSE_INVOICE_VIEW, ROLE_WAREHOUSE_INVOICE_NEW, ROLE_WAREHOUSE_INVOICE_EDIT, ROLE_WAREHOUSE_INVOICE_DELETE]

    ROLE_RESTAURANT_SENIOR_MANAGER:
      - ROLE_RESTAURANT_MANAGER
      - ROLE_RESTAURANT_DISHORDER_FREEZED
      - ROLE_RESTAURANT_CATEGORY
      - ROLE_RESTAURANT_INGREDIENT
      - ROLE_RESTAURANT_DISHMENU_CATEGORY
      - ROLE_RESTAURANT_DISHMENU_ITEM
      - ROLE_RESTAURANT_TABLE


    ROLE_RESTAURANT_MANAGER:
      - ROLE_RESTAURANT_DISHORDER

    ROLE_RESTAURANT_CATEGORY: [ROLE_RESTAURANT_CATEGORY_NEW, ROLE_RESTAURANT_CATEGORY_EDIT, ROLE_RESTAURANT_CATEGORY_DELETE]
    ROLE_RESTAURANT_INGREDIENT: [ROLE_RESTAURANT_INGREDIENT_VIEW, ROLE_RESTAURANT_INGREDIENT_NEW, ROLE_RESTAURANT_INGREDIENT_EDIT, ROLE_RESTAURANT_INGREDIENT_DELETE]
    ROLE_RESTAURANT_DISHMENU_CATEGORY: [ROLE_RESTAURANT_DISHMENU_CATEGORY_NEW, ROLE_RESTAURANT_DISHMENU_CATEGORY_EDIT, ROLE_RESTAURANT_DISHMENU_CATEGORY_DELETE]
    ROLE_RESTAURANT_DISHMENU_ITEM: [ROLE_RESTAURANT_DISHMENU_ITEM_VIEW,ROLE_RESTAURANT_DISHMENU_ITEM_NEW, ROLE_RESTAURANT_DISHMENU_ITEM_EDIT, ROLE_RESTAURANT_DISHMENU_ITEM_DELETE]
    ROLE_RESTAURANT_DISHORDER: [ROLE_RESTAURANT_DISHORDER_VIEW, ROLE_RESTAURANT_DISHORDER_NEW, ROLE_RESTAURANT_DISHORDER_EDIT, ROLE_RESTAURANT_DISHORDER_DELETE, ROLE_RESTAURANT_DISHORDER_PAY ]
    ROLE_RESTAURANT_DISHORDER_FREEZED: [ROLE_RESTAURANT_DISHORDER, ROLE_RESTAURANT_DISHORDER_FREEZED_EDIT, ROLE_RESTAURANT_DISHORDER_FREEZED_DELETE]
    ROLE_RESTAURANT_TABLE: [ ROLE_RESTAURANT_TABLE_VIEW, ROLE_RESTAURANT_TABLE_NEW, ROLE_RESTAURANT_TABLE_EDIT, ROLE_RESTAURANT_TABLE_DELETE, ROLE_RESTAURANT_TABLE_ITEM_NEW,ROLE_RESTAURANT_TABLE_ITEM_EDIT,ROLE_RESTAURANT_TABLE_ITEM_DELETE, ROLE_RESTAURANT_TABLE_CATEGORY_NEW, ROLE_RESTAURANT_TABLE_CATEGORY_EDIT, ROLE_RESTAURANT_TABLE_CATEGORY_DELETE ]

    ROLE_PACKAGE_DELETE_REASONS_CATEGORY: [ROLE_PACKAGE_DELETE_REASONS_CATEGORY_NEW, ROLE_PACKAGE_DELETE_REASONS_CATEGORY_EDIT, ROLE_PACKAGE_DELETE_REASONS_CATEGORY_DELETE]
    ROLE_PACKAGE_DELETE_REASONS: [ROLE_PACKAGE_DELETE_REASONS_ITEM_NEW, ROLE_PACKAGE_DELETE_REASONS_ITEM_EDIT, ROLE_PACKAGE_DELETE_REASONS_ITEM_DELETE]


