mbh_billing:
    resource: "@MBHBillingBundle/Controller/"
    type: annotation
    prefix: /deploy
#    defaults: { _format: 'json' }

mbh_warehouse:
    resource: "@MBHWarehouseBundle/Controller/"
    type:     annotation
    prefix:   /

mbh_client:
    resource: "@MBHClientBundle/Controller/"
    type:     annotation
    prefix:   /management/client

mbh_online:
    resource: "@MBHOnlineBundle/Controller/"
    type:     annotation
    prefix:   /management/online

mbh_channel_manager:
    resource: "@MBHChannelManagerBundle/Controller/"
    type:     annotation
    prefix:   /management/channelmanager

mbh_cash:
    resource: "@MBHCashBundle/Controller/"
    type:     annotation
    prefix:   /cash

_welcome:
    path:  /
    defaults: { _controller: MBHBaseBundle:Welcome:index}

mbh_package:
    resource: "@MBHPackageBundle/Controller/"
    type:     annotation
    prefix:   /package


mbh_price:
    resource: "@MBHPriceBundle/Controller/"
    type:     annotation
    prefix:   /price

mbh_base:
    resource: "@MBHBaseBundle/Controller/"
    type:     annotation
    prefix:   /base

mbh_export:
    resource: "@MBHBaseBundle/Controller/ExportController.php"
    type:     annotation

mbh_user:
    resource: "@MBHUserBundle/Controller/"
    type:     annotation
    prefix:   /
 
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /profile

mbh_hotel:
    resource: "@MBHHotelBundle/Controller/"
    type:     annotation
    prefix:   /management/hotel

mbh_task:
    resource: "@MBHHotelBundle/Controller/TaskController.php"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

mbh_vega:
    resource: "@MBHVegaBundle/Controller/"
    type:     annotation
    prefix:   /vega

mbh_restaurant:
    resource: "@MBHRestaurantBundle/Controller/"
    type:     annotation
    prefix:   /restaurant

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix: /api/doc
