###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################


mbh-memcached:
  image: memcached:1.4
  container_name: mbh-memcached
  ports:
    - "11211:11211"

mbh-rabbitmq:
  image: rabbitmq:latest
  container_name: mbh-rabbitmq
  hostname: "mbh-rabbitmq"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15673:15672"
    - "5673:5672"
  labels:
    NAME: "mbh-rabbitmq"
  volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

mbh-redis:
  image: redis:latest
  container_name: mbh-redis
  ports:
     - "6378:6379"

mbh-mongo:
  image: mongo:3.6
  container_name: mbh-mongo
  command: mongod --setParameter failIndexKeyTooLong=false
  volumes:
      - mongo_data:/data/db
  ports:
     - "27018:27017"

mbh-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: mbh-php-fpm
  volumes:
    - ..:/var/www/mbh
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
    - ./php-fpm/start.sh:/start.sh
    - ./php-fpm/fish:/root/.config/fish/functions
    - /tmp/:/tmp/
    - ./php-fpm/keys:/root/.ssh
  links:
    - mbh-memcached
    - mbh-mongo
    - mbh-rabbitmq
    - mbh-redis

mbh-php-cli:
  build: .
  dockerfile: php-cli/Dockerfile
  container_name: mbh-php-cli
  volumes:
      - ..:/var/www/mbh
      - ./php-cli/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
      - ./php-cli/fish:/root/.config/fish/functions
      - /tmp/:/tmp/
  links:
    - mbh-memcached
    - mbh-mongo
    - mbh-rabbitmq
    - mbh-redis
  ports:
    - "8181:8181"

mbh-webserver:
  image: phpdockerio/nginx:latest
  container_name: mbh-webserver
  volumes:
      - ..:/var/www/mbh
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi_param_client:/etc/nginx/fastcgi_param_client
      - ./nginx/cert/:/etc/cert/
  ports:
   - "9090:80"
   - "9443:443"
  links:
   - mbh-php-fpm
