parameters:
    online_booking:
        request_search_url: '/mbresults/'
        payonlineurl: http://azovsky-billing.com/pay/
        use_charts: false
        add_search_dates: 1
        show_all: false
        hotels_links:
            56fbd22174eb5383728b4567: '/azovsky/'
            5705190e74eb53461c8b4916: '/azovland/'
            eat: '/shvedskiy-stol/'
        show_specials: true
        show_special_restrict: 10
#        special_list_sort: byDate
        special_list_sort: byPrice


    online_reservation_manager_email: "mail@azovsky.ru"
    offera: "https://yadi.sk/i/aSRIUwg0zjWVw"

    domain_access_control_prod: 'http://testaz.maxibooking.ru'
    domain_access_control_dev: 'http://localhost:8080'

    online_left_rooms:
        min_threshold: 3
        max_threshold: 7
